name: 'My Custom Action'
description: 'This is a custom GitHub Action.'
author: 'Your Name'

inputs:
  chart-data:
    description: 'JSON data for the chart'
    required: true
  github-token:
    description: 'GitHub token for pushing to gh-pages'
    required: true

outputs:
  html-report:
    description: 'The generated HTML report with the chart'

runs:
  using: 'node20'
  main: 'dist/index.js'
