name: 'Test a custom action'

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Run my custom action'
        id: test
        uses: ./
        with:
          chart-data: '{ "labels": ["Red", "Blue", "Yellow", "Green", "Purple", "Orange"], "datasets": [{ "label": "# of Votes", "data": [12, 19, 3, 5, 2, 3], "backgroundColor": ["rgba(255, 99, 132, 0.2)", "rgba(54, 162, 235, 0.2)", "rgba(255, 206, 86, 0.2)", "rgba(75, 192, 192, 0.2)", "rgba(153, 102, 255, 0.2)", "rgba(255, 159, 64, 0.2)"], "borderColor": ["rgba(255, 99, 132, 1)", "rgba(54, 162, 235, 1)", "rgba(255, 206, 86, 1)", "rgba(75, 192, 192, 1)", "rgba(153, 102, 255, 1)", "rgba(255, 159, 64, 1)"], "borderWidth": 1 }] }'

      - name: 'Write report to file'
        env:
          HTML_REPORT: ${{ steps.test.outputs.html-report }}
        run: echo "$HTML_REPORT" > report.html

      - name: 'Upload HTML report'
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: report.html
