name: 'Test a custom action'

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Run my custom action'
        uses: ./ 
        with:
          greeting: 'test'
